// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: BSD-3-Clause

// This file is generated
// Do not edit manually

#include "opencl.std.hpp"

namespace tinytc::spv {

auto to_string(OpenCLEntrypoint ep) -> char const * {
    switch (ep) {
    case OpenCLEntrypoint::acos:
        return "acos";
    case OpenCLEntrypoint::acosh:
        return "acosh";
    case OpenCLEntrypoint::acospi:
        return "acospi";
    case OpenCLEntrypoint::asin:
        return "asin";
    case OpenCLEntrypoint::asinh:
        return "asinh";
    case OpenCLEntrypoint::asinpi:
        return "asinpi";
    case OpenCLEntrypoint::atan:
        return "atan";
    case OpenCLEntrypoint::atan2:
        return "atan2";
    case OpenCLEntrypoint::atanh:
        return "atanh";
    case OpenCLEntrypoint::atanpi:
        return "atanpi";
    case OpenCLEntrypoint::atan2pi:
        return "atan2pi";
    case OpenCLEntrypoint::cbrt:
        return "cbrt";
    case OpenCLEntrypoint::ceil:
        return "ceil";
    case OpenCLEntrypoint::copysign:
        return "copysign";
    case OpenCLEntrypoint::cos:
        return "cos";
    case OpenCLEntrypoint::cosh:
        return "cosh";
    case OpenCLEntrypoint::cospi:
        return "cospi";
    case OpenCLEntrypoint::erfc:
        return "erfc";
    case OpenCLEntrypoint::erf:
        return "erf";
    case OpenCLEntrypoint::exp:
        return "exp";
    case OpenCLEntrypoint::exp2:
        return "exp2";
    case OpenCLEntrypoint::exp10:
        return "exp10";
    case OpenCLEntrypoint::expm1:
        return "expm1";
    case OpenCLEntrypoint::fabs:
        return "fabs";
    case OpenCLEntrypoint::fdim:
        return "fdim";
    case OpenCLEntrypoint::floor:
        return "floor";
    case OpenCLEntrypoint::fma:
        return "fma";
    case OpenCLEntrypoint::fmax:
        return "fmax";
    case OpenCLEntrypoint::fmin:
        return "fmin";
    case OpenCLEntrypoint::fmod:
        return "fmod";
    case OpenCLEntrypoint::fract:
        return "fract";
    case OpenCLEntrypoint::frexp:
        return "frexp";
    case OpenCLEntrypoint::hypot:
        return "hypot";
    case OpenCLEntrypoint::ilogb:
        return "ilogb";
    case OpenCLEntrypoint::ldexp:
        return "ldexp";
    case OpenCLEntrypoint::lgamma:
        return "lgamma";
    case OpenCLEntrypoint::lgamma_r:
        return "lgamma_r";
    case OpenCLEntrypoint::log:
        return "log";
    case OpenCLEntrypoint::log2:
        return "log2";
    case OpenCLEntrypoint::log10:
        return "log10";
    case OpenCLEntrypoint::log1p:
        return "log1p";
    case OpenCLEntrypoint::logb:
        return "logb";
    case OpenCLEntrypoint::mad:
        return "mad";
    case OpenCLEntrypoint::maxmag:
        return "maxmag";
    case OpenCLEntrypoint::minmag:
        return "minmag";
    case OpenCLEntrypoint::modf:
        return "modf";
    case OpenCLEntrypoint::nan:
        return "nan";
    case OpenCLEntrypoint::nextafter:
        return "nextafter";
    case OpenCLEntrypoint::pow:
        return "pow";
    case OpenCLEntrypoint::pown:
        return "pown";
    case OpenCLEntrypoint::powr:
        return "powr";
    case OpenCLEntrypoint::remainder:
        return "remainder";
    case OpenCLEntrypoint::remquo:
        return "remquo";
    case OpenCLEntrypoint::rint:
        return "rint";
    case OpenCLEntrypoint::rootn:
        return "rootn";
    case OpenCLEntrypoint::round:
        return "round";
    case OpenCLEntrypoint::rsqrt:
        return "rsqrt";
    case OpenCLEntrypoint::sin:
        return "sin";
    case OpenCLEntrypoint::sincos:
        return "sincos";
    case OpenCLEntrypoint::sinh:
        return "sinh";
    case OpenCLEntrypoint::sinpi:
        return "sinpi";
    case OpenCLEntrypoint::sqrt:
        return "sqrt";
    case OpenCLEntrypoint::tan:
        return "tan";
    case OpenCLEntrypoint::tanh:
        return "tanh";
    case OpenCLEntrypoint::tanpi:
        return "tanpi";
    case OpenCLEntrypoint::tgamma:
        return "tgamma";
    case OpenCLEntrypoint::trunc:
        return "trunc";
    case OpenCLEntrypoint::half_cos:
        return "half_cos";
    case OpenCLEntrypoint::half_divide:
        return "half_divide";
    case OpenCLEntrypoint::half_exp:
        return "half_exp";
    case OpenCLEntrypoint::half_exp2:
        return "half_exp2";
    case OpenCLEntrypoint::half_exp10:
        return "half_exp10";
    case OpenCLEntrypoint::half_log:
        return "half_log";
    case OpenCLEntrypoint::half_log2:
        return "half_log2";
    case OpenCLEntrypoint::half_log10:
        return "half_log10";
    case OpenCLEntrypoint::half_powr:
        return "half_powr";
    case OpenCLEntrypoint::half_recip:
        return "half_recip";
    case OpenCLEntrypoint::half_rsqrt:
        return "half_rsqrt";
    case OpenCLEntrypoint::half_sin:
        return "half_sin";
    case OpenCLEntrypoint::half_sqrt:
        return "half_sqrt";
    case OpenCLEntrypoint::half_tan:
        return "half_tan";
    case OpenCLEntrypoint::native_cos:
        return "native_cos";
    case OpenCLEntrypoint::native_divide:
        return "native_divide";
    case OpenCLEntrypoint::native_exp:
        return "native_exp";
    case OpenCLEntrypoint::native_exp2:
        return "native_exp2";
    case OpenCLEntrypoint::native_exp10:
        return "native_exp10";
    case OpenCLEntrypoint::native_log:
        return "native_log";
    case OpenCLEntrypoint::native_log2:
        return "native_log2";
    case OpenCLEntrypoint::native_log10:
        return "native_log10";
    case OpenCLEntrypoint::native_powr:
        return "native_powr";
    case OpenCLEntrypoint::native_recip:
        return "native_recip";
    case OpenCLEntrypoint::native_rsqrt:
        return "native_rsqrt";
    case OpenCLEntrypoint::native_sin:
        return "native_sin";
    case OpenCLEntrypoint::native_sqrt:
        return "native_sqrt";
    case OpenCLEntrypoint::native_tan:
        return "native_tan";
    case OpenCLEntrypoint::s_abs:
        return "s_abs";
    case OpenCLEntrypoint::s_abs_diff:
        return "s_abs_diff";
    case OpenCLEntrypoint::s_add_sat:
        return "s_add_sat";
    case OpenCLEntrypoint::u_add_sat:
        return "u_add_sat";
    case OpenCLEntrypoint::s_hadd:
        return "s_hadd";
    case OpenCLEntrypoint::u_hadd:
        return "u_hadd";
    case OpenCLEntrypoint::s_rhadd:
        return "s_rhadd";
    case OpenCLEntrypoint::u_rhadd:
        return "u_rhadd";
    case OpenCLEntrypoint::s_clamp:
        return "s_clamp";
    case OpenCLEntrypoint::u_clamp:
        return "u_clamp";
    case OpenCLEntrypoint::clz:
        return "clz";
    case OpenCLEntrypoint::ctz:
        return "ctz";
    case OpenCLEntrypoint::s_mad_hi:
        return "s_mad_hi";
    case OpenCLEntrypoint::u_mad_sat:
        return "u_mad_sat";
    case OpenCLEntrypoint::s_mad_sat:
        return "s_mad_sat";
    case OpenCLEntrypoint::s_max:
        return "s_max";
    case OpenCLEntrypoint::u_max:
        return "u_max";
    case OpenCLEntrypoint::s_min:
        return "s_min";
    case OpenCLEntrypoint::u_min:
        return "u_min";
    case OpenCLEntrypoint::s_mul_hi:
        return "s_mul_hi";
    case OpenCLEntrypoint::rotate:
        return "rotate";
    case OpenCLEntrypoint::s_sub_sat:
        return "s_sub_sat";
    case OpenCLEntrypoint::u_sub_sat:
        return "u_sub_sat";
    case OpenCLEntrypoint::u_upsample:
        return "u_upsample";
    case OpenCLEntrypoint::s_upsample:
        return "s_upsample";
    case OpenCLEntrypoint::popcount:
        return "popcount";
    case OpenCLEntrypoint::s_mad24:
        return "s_mad24";
    case OpenCLEntrypoint::u_mad24:
        return "u_mad24";
    case OpenCLEntrypoint::s_mul24:
        return "s_mul24";
    case OpenCLEntrypoint::u_mul24:
        return "u_mul24";
    case OpenCLEntrypoint::u_abs:
        return "u_abs";
    case OpenCLEntrypoint::u_abs_diff:
        return "u_abs_diff";
    case OpenCLEntrypoint::u_mul_hi:
        return "u_mul_hi";
    case OpenCLEntrypoint::u_mad_hi:
        return "u_mad_hi";
    case OpenCLEntrypoint::fclamp:
        return "fclamp";
    case OpenCLEntrypoint::degrees:
        return "degrees";
    case OpenCLEntrypoint::fmax_common:
        return "fmax_common";
    case OpenCLEntrypoint::fmin_common:
        return "fmin_common";
    case OpenCLEntrypoint::mix:
        return "mix";
    case OpenCLEntrypoint::radians:
        return "radians";
    case OpenCLEntrypoint::step:
        return "step";
    case OpenCLEntrypoint::smoothstep:
        return "smoothstep";
    case OpenCLEntrypoint::sign:
        return "sign";
    case OpenCLEntrypoint::cross:
        return "cross";
    case OpenCLEntrypoint::distance:
        return "distance";
    case OpenCLEntrypoint::length:
        return "length";
    case OpenCLEntrypoint::normalize:
        return "normalize";
    case OpenCLEntrypoint::fast_distance:
        return "fast_distance";
    case OpenCLEntrypoint::fast_length:
        return "fast_length";
    case OpenCLEntrypoint::fast_normalize:
        return "fast_normalize";
    case OpenCLEntrypoint::bitselect:
        return "bitselect";
    case OpenCLEntrypoint::select:
        return "select";
    case OpenCLEntrypoint::vloadn:
        return "vloadn";
    case OpenCLEntrypoint::vstoren:
        return "vstoren";
    case OpenCLEntrypoint::vload_half:
        return "vload_half";
    case OpenCLEntrypoint::vload_halfn:
        return "vload_halfn";
    case OpenCLEntrypoint::vstore_half:
        return "vstore_half";
    case OpenCLEntrypoint::vstore_half_r:
        return "vstore_half_r";
    case OpenCLEntrypoint::vstore_halfn:
        return "vstore_halfn";
    case OpenCLEntrypoint::vstore_halfn_r:
        return "vstore_halfn_r";
    case OpenCLEntrypoint::vloada_halfn:
        return "vloada_halfn";
    case OpenCLEntrypoint::vstorea_halfn:
        return "vstorea_halfn";
    case OpenCLEntrypoint::vstorea_halfn_r:
        return "vstorea_halfn_r";
    case OpenCLEntrypoint::shuffle:
        return "shuffle";
    case OpenCLEntrypoint::shuffle2:
        return "shuffle2";
    case OpenCLEntrypoint::printf:
        return "printf";
    case OpenCLEntrypoint::prefetch:
        return "prefetch";
    }
    return "unknown";
}

} // namespace tinytc::spv
